export default [
  {
    id: 1,
    question: "What is the capital of France?",
    options: ["A) Berlin", "B) Madrid", "C) Paris", "D) Rome"],
    answer: "C) Paris",
  },
  {
    id: 2,
    question: "Which planet is known as the Red Planet?",
    options: ["A) Earth", "B) Mars", "C) Jupiter", "D) Venus"],
    answer: "B) Mars",
  },
  {
    id: 3,
    question: "Who wrote 'To Kill a Mockingbird'?",
    options: [
      "A) Harper Lee",
      "B) Mark Twain",
      "C) Jane Austen",
      "D) Ernest Hemingway",
    ],
    answer: "A) Harper Lee",
  },
  {
    id: 4,
    question: "What is the largest ocean on Earth?",
    options: [
      "A) Atlantic Ocean",
      "B) Indian Ocean",
      "C) Arctic Ocean",
      "D) Pacific Ocean",
    ],
    answer: "D) Pacific Ocean",
  },
  {
    id: 5,
    question: "In which year did the Titanic sink?",
    options: ["A) 1912", "B) 1905", "C) 1920", "D) 1898"],
    answer: "A) 1912",
  },
  {
    id: 6,
    question: "Who painted the Mona Lisa?",
    options: [
      "A) Vincent van Gogh",
      "B) Leonardo da Vinci",
      "C) Pablo Picasso",
      "D) Michelangelo",
    ],
    answer: "B) Leonardo da Vinci",
  },
  {
    id: 7,
    question: "What is the chemical symbol for gold?",
    options: ["A) Ag", "B) Au", "C) Fe", "D) Cu"],
    answer: "B) Au",
  },
  {
    id: 8,
    question: "Which country is home to the kangaroo?",
    options: ["A) New Zealand", "B) South Africa", "C) Australia", "D) Brazil"],
    answer: "C) Australia",
  },
  {
    id: 9,
    question: "What is the largest planet in our solar system?",
    options: ["A) Earth", "B) Mars", "C) Jupiter", "D) Saturn"],
    answer: "C) Jupiter",
  },
  {
    id: 10,
    question: "Who wrote 'Romeo and Juliet'?",
    options: [
      "A) Charles Dickens",
      "B) William Shakespeare",
      "C) Jane Austen",
      "D) Mark Twain",
    ],
    answer: "B) William Shakespeare",
  },
  {
    id: 11,
    question: "What is the capital of Japan?",
    options: ["A) Seoul", "B) Beijing", "C) Tokyo", "D) Bangkok"],
    answer: "C) Tokyo",
  },
  {
    id: 12,
    question: "Which element has the chemical symbol 'O'?",
    options: ["A) Oxygen", "B) Gold", "C) Silver", "D) Iron"],
    answer: "A) Oxygen",
  },
  {
    id: 13,
    question: "Who was the first person to step on the moon?",
    options: [
      "A) Buzz Aldrin",
      "B) Yuri Gagarin",
      "C) Neil Armstrong",
      "D) John Glenn",
    ],
    answer: "C) Neil Armstrong",
  },
  {
    id: 14,
    question: "What is the largest mammal in the world?",
    options: [
      "A) African Elephant",
      "B) Blue Whale",
      "C) Giraffe",
      "D) Polar Bear",
    ],
    answer: "B) Blue Whale",
  },
  {
    id: 15,
    question: "Which of these is not a primary color?",
    options: ["A) Red", "B) Blue", "C) Yellow", "D) Green"],
    answer: "D) Green",
  },
  {
    id: 16,
    question: "What is the capital of Australia?",
    options: ["A) Sydney", "B) Melbourne", "C) Canberra", "D) Perth"],
    answer: "C) Canberra",
  },
  {
    id: 17,
    question: "Who invented the telephone?",
    options: [
      "A) Thomas Edison",
      "B) Alexander Graham Bell",
      "C) Nikola Tesla",
      "D) Guglielmo Marconi",
    ],
    answer: "B) Alexander Graham Bell",
  },
  {
    id: 18,
    question: "What is the smallest prime number?",
    options: ["A) 0", "B) 1", "C) 2", "D) 3"],
    answer: "C) 2",
  },
  {
    id: 19,
    question: "Which country is home to the Great Barrier Reef?",
    options: ["A) Brazil", "B) Australia", "C) Indonesia", "D) Philippines"],
    answer: "B) Australia",
  },
  {
    id: 20,
    question: "Who wrote '1984'?",
    options: [
      "A) Aldous Huxley",
      "B) George Orwell",
      "C) Ray Bradbury",
      "D) H.G. Wells",
    ],
    answer: "B) George Orwell",
  },
  {
    id: 21,
    question: "What is the capital of Canada?",
    options: ["A) Toronto", "B) Vancouver", "C) Montreal", "D) Ottawa"],
    answer: "D) Ottawa",
  },
  {
    id: 22,
    question: "Which planet is known as the 'Morning Star'?",
    options: ["A) Mars", "B) Venus", "C) Jupiter", "D) Mercury"],
    answer: "B) Venus",
  },
  {
    id: 23,
    question: "Who painted 'Starry Night'?",
    options: [
      "A) Claude Monet",
      "B) Vincent van Gogh",
      "C) Pablo Picasso",
      "D) Salvador Dali",
    ],
    answer: "B) Vincent van Gogh",
  },
  {
    id: 24,
    question: "What is the largest desert in the world?",
    options: ["A) Gobi", "B) Kalahari", "C) Sahara", "D) Antarctic"],
    answer: "D) Antarctic",
  },
  {
    id: 25,
    question: "Who discovered penicillin?",
    options: [
      "A) Marie Curie",
      "B) Louis Pasteur",
      "C) Alexander Fleming",
      "D) Joseph Lister",
    ],
    answer: "C) Alexander Fleming",
  },
  {
    id: 26,
    question: "What is the capital of Brazil?",
    options: [
      "A) São Paulo",
      "B) Rio de Janeiro",
      "C) Brasília",
      "D) Salvador",
    ],
    answer: "C) Brasília",
  },
  {
    id: 27,
    question: "Which element has the atomic number 1?",
    options: ["A) Helium", "B) Hydrogen", "C) Carbon", "D) Oxygen"],
    answer: "B) Hydrogen",
  },
  {
    id: 28,
    question: "Who composed 'The Four Seasons'?",
    options: [
      "A) Johann Sebastian Bach",
      "B) Wolfgang Amadeus Mozart",
      "C) Ludwig van Beethoven",
      "D) Antonio Vivaldi",
    ],
    answer: "D) Antonio Vivaldi",
  },
  {
    id: 29,
    question: "What is the largest bird in the world?",
    options: ["A) Ostrich", "B) Emu", "C) Albatross", "D) Condor"],
    answer: "A) Ostrich",
  },
  {
    id: 30,
    question: "Which country is home to the Taj Mahal?",
    options: ["A) India", "B) Egypt", "C) Turkey", "D) Iran"],
    answer: "A) India",
  },
  {
    id: 31,
    question: "Who discovered gravity?",
    options: [
      "A) Albert Einstein",
      "B) Isaac Newton",
      "C) Galileo Galilei",
      "D) Stephen Hawking",
    ],
    answer: "B) Isaac Newton",
  },
  {
    id: 32,
    question: "What is the capital of Russia?",
    options: ["A) St. Petersburg", "B) Kiev", "C) Moscow", "D) Minsk"],
    answer: "C) Moscow",
  },
  {
    id: 33,
    question: "Which planet is known as the 'Blue Planet'?",
    options: ["A) Neptune", "B) Uranus", "C) Earth", "D) Mars"],
    answer: "C) Earth",
  },
  {
    id: 34,
    question: "Who wrote 'The Great Gatsby'?",
    options: [
      "A) Ernest Hemingway",
      "B) F. Scott Fitzgerald",
      "C) John Steinbeck",
      "D) William Faulkner",
    ],
    answer: "B) F. Scott Fitzgerald",
  },
  {
    id: 35,
    question: "What is the smallest country in the world?",
    options: [
      "A) Monaco",
      "B) San Marino",
      "C) Vatican City",
      "D) Liechtenstein",
    ],
    answer: "C) Vatican City",
  },
  {
    id: 36,
    question: "Who invented the World Wide Web?",
    options: [
      "A) Steve Jobs",
      "B) Bill Gates",
      "C) Tim Berners-Lee",
      "D) Mark Zuckerberg",
    ],
    answer: "C) Tim Berners-Lee",
  },
  {
    id: 37,
    question: "What is the capital of Spain?",
    options: ["A) Barcelona", "B) Seville", "C) Valencia", "D) Madrid"],
    answer: "D) Madrid",
  },
  {
    id: 38,
    question: "Which is the longest river in the world?",
    options: ["A) Amazon", "B) Nile", "C) Yangtze", "D) Mississippi"],
    answer: "B) Nile",
  },
  {
    id: 39,
    question: "Who painted the 'The Last Supper'?",
    options: [
      "A) Michelangelo",
      "B) Raphael",
      "C) Leonardo da Vinci",
      "D) Donatello",
    ],
    answer: "C) Leonardo da Vinci",
  },
  {
    id: 40,
    question: "What is the largest country by land area?",
    options: ["A) China", "B) United States", "C) Canada", "D) Russia"],
    answer: "D) Russia",
  },
  {
    id: 41,
    question: "Who developed the theory of relativity?",
    options: [
      "A) Isaac Newton",
      "B) Stephen Hawking",
      "C) Albert Einstein",
      "D) Niels Bohr",
    ],
    answer: "C) Albert Einstein",
  },
  {
    id: 42,
    question: "What is the capital of South Africa?",
    options: ["A) Johannesburg", "B) Cape Town", "C) Durban", "D) Pretoria"],
    answer: "D) Pretoria",
  },
  {
    id: 43,
    question: "Which element has the chemical symbol 'Fe'?",
    options: ["A) Iron", "B) Gold", "C) Silver", "D) Copper"],
    answer: "A) Iron",
  },
  {
    id: 44,
    question: "Who wrote 'Pride and Prejudice'?",
    options: [
      "A) Emily Bronte",
      "B) Jane Austen",
      "C) Charlotte Bronte",
      "D) Virginia Woolf",
    ],
    answer: "B) Jane Austen",
  },
  {
    id: 45,
    question: "What is the largest waterfall in the world?",
    options: [
      "A) Niagara Falls",
      "B) Victoria Falls",
      "C) Angel Falls",
      "D) Iguazu Falls",
    ],
    answer: "C) Angel Falls",
  },
  {
    id: 46,
    question: "Who is known as the father of modern physics?",
    options: [
      "A) Isaac Newton",
      "B) Albert Einstein",
      "C) Galileo Galilei",
      "D) Stephen Hawking",
    ],
    answer: "B) Albert Einstein",
  },
  {
    id: 47,
    question: "What is the capital of China?",
    options: ["A) Shanghai", "B) Hong Kong", "C) Beijing", "D) Guangzhou"],
    answer: "C) Beijing",
  },
  {
    id: 48,
    question: "Which is the smallest planet in our solar system?",
    options: ["A) Mars", "B) Venus", "C) Mercury", "D) Pluto"],
    answer: "C) Mercury",
  },
  {
    id: 49,
    question: "Who painted the 'Girl with a Pearl Earring'?",
    options: [
      "A) Rembrandt",
      "B) Johannes Vermeer",
      "C) Vincent van Gogh",
      "D) Pablo Picasso",
    ],
    answer: "B) Johannes Vermeer",
  },
  {
    id: 50,
    question: "What is the deepest point in the Earth's oceans?",
    options: [
      "A) Mariana Trench",
      "B) Tonga Trench",
      "C) Philippine Trench",
      "D) Puerto Rico Trench",
    ],
    answer: "A) Mariana Trench",
  },
  {
    id: 51,
    question: "What is the capital of Italy?",
    options: ["A) Venice", "B) Milan", "C) Rome", "D) Florence"],
    answer: "C) Rome",
  },
  {
    id: 52,
    question: "Which element has the chemical symbol 'Na'?",
    options: ["A) Nitrogen", "B) Sodium", "C) Neon", "D) Nickel"],
    answer: "B) Sodium",
  },
  {
    id: 53,
    question: "Who wrote 'The Catcher in the Rye'?",
    options: [
      "A) J.D. Salinger",
      "B) Ernest Hemingway",
      "C) F. Scott Fitzgerald",
      "D) John Steinbeck",
    ],
    answer: "A) J.D. Salinger",
  },
  {
    id: 54,
    question: "What is the largest continent by land area?",
    options: ["A) Africa", "B) North America", "C) Asia", "D) Europe"],
    answer: "C) Asia",
  },
  {
    id: 55,
    question: "Who discovered radioactivity?",
    options: [
      "A) Marie Curie",
      "B) Albert Einstein",
      "C) Isaac Newton",
      "D) Niels Bohr",
    ],
    answer: "A) Marie Curie",
  },
  {
    id: 56,
    question: "What is the capital of Egypt?",
    options: ["A) Alexandria", "B) Cairo", "C) Luxor", "D) Giza"],
    answer: "B) Cairo",
  },
  {
    id: 57,
    question: "Which planet is known as the 'Ice Giant'?",
    options: ["A) Neptune", "B) Uranus", "C) Saturn", "D) Jupiter"],
    answer: "B) Uranus",
  },
  {
    id: 58,
    question: "Who painted 'The Persistence of Memory'?",
    options: [
      "A) Pablo Picasso",
      "B) Salvador Dali",
      "C) Frida Kahlo",
      "D) Andy Warhol",
    ],
    answer: "B) Salvador Dali",
  },
  {
    id: 59,
    question: "What is the smallest bone in the human body?",
    options: ["A) Stapes", "B) Femur", "C) Tibia", "D) Radius"],
    answer: "A) Stapes",
  },
  {
    id: 60,
    question: "Who is credited with inventing the light bulb?",
    options: [
      "A) Nikola Tesla",
      "B) Thomas Edison",
      "C) Alexander Graham Bell",
      "D) Benjamin Franklin",
    ],
    answer: "B) Thomas Edison",
  },
  {
    id: 61,
    question: "What is the capital of Germany?",
    options: ["A) Munich", "B) Hamburg", "C) Frankfurt", "D) Berlin"],
    answer: "D) Berlin",
  },
  {
    id: 62,
    question: "Which is the largest species of shark?",
    options: [
      "A) Great White Shark",
      "B) Whale Shark",
      "C) Hammerhead Shark",
      "D) Tiger Shark",
    ],
    answer: "B) Whale Shark",
  },
  {
    id: 63,
    question: "Who wrote 'War and Peace'?",
    options: [
      "A) Fyodor Dostoevsky",
      "B) Leo Tolstoy",
      "C) Anton Chekhov",
      "D) Vladimir Nabokov",
    ],
    answer: "B) Leo Tolstoy",
  },
  {
    id: 64,
    question: "What is the hardest natural substance on Earth?",
    options: ["A) Gold", "B) Iron", "C) Diamond", "D) Quartz"],
    answer: "C) Diamond",
  },
  {
    id: 65,
    question: "Who is known as the father of computer science?",
    options: [
      "A) Steve Jobs",
      "B) Bill Gates",
      "C) Alan Turing",
      "D) Charles Babbage",
    ],
    answer: "C) Alan Turing",
  },
  {
    id: 66,
    question: "What is the capital of Argentina?",
    options: ["A) Santiago", "B) Lima", "C) Buenos Aires", "D) Montevideo"],
    answer: "C) Buenos Aires",
  },
  {
    id: 67,
    question: "Which planet has the Great Red Spot?",
    options: ["A) Mars", "B) Venus", "C) Jupiter", "D) Saturn"],
    answer: "C) Jupiter",
  },
  {
    id: 68,
    question: "Who composed the opera 'The Magic Flute'?",
    options: [
      "A) Ludwig van Beethoven",
      "B) Johann Sebastian Bach",
      "C) Wolfgang Amadeus Mozart",
      "D) Richard Wagner",
    ],
    answer: "C) Wolfgang Amadeus Mozart",
  },
  {
    id: 69,
    question: "What is the largest organ in the human body?",
    options: ["A) Heart", "B) Liver", "C) Brain", "D) Skin"],
    answer: "D) Skin",
  },
  {
    id: 70,
    question: "Who developed the polio vaccine?",
    options: [
      "A) Jonas Salk",
      "B) Louis Pasteur",
      "C) Edward Jenner",
      "D) Alexander Fleming",
    ],
    answer: "A) Jonas Salk",
  },
  {
    id: 71,
    question: "What is the capital of Turkey?",
    options: ["A) Istanbul", "B) Ankara", "C) Izmir", "D) Antalya"],
    answer: "B) Ankara",
  },
  {
    id: 72,
    question: "Which is the largest species of big cat?",
    options: ["A) Lion", "B) Tiger", "C) Leopard", "D) Jaguar"],
    answer: "B) Tiger",
  },
  {
    id: 73,
    question: "Who wrote 'One Hundred Years of Solitude'?",
    options: [
      "A) Pablo Neruda",
      "B) Gabriel García Márquez",
      "C) Jorge Luis Borges",
      "D) Isabel Allende",
    ],
    answer: "B) Gabriel García Márquez",
  },
  {
    id: 74,
    question: "What is the most abundant gas in Earth's atmosphere?",
    options: ["A) Oxygen", "B) Carbon Dioxide", "C) Nitrogen", "D) Hydrogen"],
    answer: "C) Nitrogen",
  },
  {
    id: 75,
    question:
      "Who is credited with the theory of evolution by natural selection?",
    options: [
      "A) Gregor Mendel",
      "B) Charles Darwin",
      "C) Lamarck",
      "D) Alfred Russel Wallace",
    ],
    answer: "B) Charles Darwin",
  },
  {
    id: 76,
    question: "What is the capital of South Korea?",
    options: ["A) Busan", "B) Incheon", "C) Seoul", "D) Daegu"],
    answer: "C) Seoul",
  },
  {
    id: 77,
    question: "Which element has the atomic number 79?",
    options: ["A) Silver", "B) Gold", "C) Platinum", "D) Mercury"],
    answer: "B) Gold",
  },
  {
    id: 78,
    question: "Who painted 'The Scream'?",
    options: [
      "A) Edvard Munch",
      "B) Gustav Klimt",
      "C) Claude Monet",
      "D) Henri Matisse",
    ],
    answer: "A) Edvard Munch",
  },
  {
    id: 79,
    question: "What is the smallest prime number greater than 100?",
    options: ["A) 101", "B) 103", "C) 107", "D) 109"],
    answer: "A) 101",
  },
  {
    id: 80,
    question: "Who invented the telephone?",
    options: [
      "A) Thomas Edison",
      "B) Nikola Tesla",
      "C) Alexander Graham Bell",
      "D) Guglielmo Marconi",
    ],
    answer: "C) Alexander Graham Bell",
  },
  {
    id: 81,
    question: "What is the capital of Mexico?",
    options: ["A) Guadalajara", "B) Cancún", "C) Monterrey", "D) Mexico City"],
    answer: "D) Mexico City",
  },
  {
    id: 82,
    question: "Which is the largest species of penguin?",
    options: [
      "A) Emperor Penguin",
      "B) King Penguin",
      "C) Gentoo Penguin",
      "D) Adélie Penguin",
    ],
    answer: "A) Emperor Penguin",
  },
  {
    id: 83,
    question: "Who wrote 'The Odyssey'?",
    options: ["A) Sophocles", "B) Homer", "C) Euripides", "D) Aeschylus"],
    answer: "B) Homer",
  },
  {
    id: 84,
    question: "What is the boiling point of water in Celsius?",
    options: ["A) 90°C", "B) 100°C", "C) 110°C", "D) 212°C"],
    answer: "B) 100°C",
  },
  {
    id: 85,
    question: "Who discovered the structure of DNA?",
    options: [
      "A) Watson and Crick",
      "B) Franklin and Wilkins",
      "C) Pauling and Corey",
      "D) Avery, MacLeod, and McCarty",
    ],
    answer: "A) Watson and Crick",
  },
  {
    id: 86,
    question: "What is the capital of Sweden?",
    options: ["A) Gothenburg", "B) Malmö", "C) Uppsala", "D) Stockholm"],
    answer: "D) Stockholm",
  },
  {
    id: 87,
    question: "Which planet is closest to the sun?",
    options: ["A) Venus", "B) Mars", "C) Mercury", "D) Earth"],
    answer: "C) Mercury",
  },
  {
    id: 88,
    question: "Who composed 'The Nutcracker'?",
    options: [
      "A) Igor Stravinsky",
      "B) Sergei Rachmaninoff",
      "C) Pyotr Ilyich Tchaikovsky",
      "D) Dmitri Shostakovich",
    ],
    answer: "C) Pyotr Ilyich Tchaikovsky",
  },
  {
    id: 89,
    question: "What is the largest artery in the human body?",
    options: [
      "A) Carotid artery",
      "B) Aorta",
      "C) Pulmonary artery",
      "D) Femoral artery",
    ],
    answer: "B) Aorta",
  },
  {
    id: 90,
    question: "Who is known as the father of modern chemistry?",
    options: [
      "A) Robert Boyle",
      "B) Antoine Lavoisier",
      "C) Dmitri Mendeleev",
      "D) John Dalton",
    ],
    answer: "B) Antoine Lavoisier",
  },
  {
    id: 91,
    question: "What is the capital of India?",
    options: ["A) Mumbai", "B) Kolkata", "C) New Delhi", "D) Chennai"],
    answer: "C) New Delhi",
  },
  {
    id: 92,
    question: "Which is the largest species of bear?",
    options: [
      "A) Grizzly Bear",
      "B) Polar Bear",
      "C) Kodiak Bear",
      "D) Spectacled Bear",
    ],
    answer: "B) Polar Bear",
  },
  {
    id: 93,
    question: "Who wrote 'The Picture of Dorian Gray'?",
    options: [
      "A) Oscar Wilde",
      "B) Charles Dickens",
      "C) Emily Brontë",
      "D) Thomas Hardy",
    ],
    answer: "A) Oscar Wilde",
  },
  {
    id: 94,
    question: "What is the speed of light in vacuum?",
    options: [
      "A) 299,792 km/s",
      "B) 300,000 km/s",
      "C) 310,000 km/s",
      "D) 320,000 km/s",
    ],
    answer: "A) 299,792 km/s",
  },
  {
    id: 95,
    question: "Who developed the theory of psychoanalysis?",
    options: [
      "A) Carl Jung",
      "B) Sigmund Freud",
      "C) B.F. Skinner",
      "D) Ivan Pavlov",
    ],
    answer: "B) Sigmund Freud",
  },
  {
    id: 96,
    question: "What is the capital of Nigeria?",
    options: ["A) Lagos", "B) Abuja", "C) Kano", "D) Ibadan"],
    answer: "B) Abuja",
  },
  {
    id: 97,
    question: "Which element has the chemical symbol 'K'?",
    options: ["A) Krypton", "B) Potassium", "C) Calcium", "D) Copper"],
    answer: "B) Potassium",
  },
  {
    id: 98,
    question: "Who painted 'The Birth of Venus'?",
    options: [
      "A) Leonardo da Vinci",
      "B) Michelangelo",
      "C) Sandro Botticelli",
      "D) Raphael",
    ],
    answer: "C) Sandro Botticelli",
  },
  {
    id: 99,
    question: "What is the largest moon of Saturn?",
    options: ["A) Enceladus", "B) Titan", "C) Mimas", "D) Rhea"],
    answer: "B) Titan",
  },
  {
    id: 100,
    question:
      "Who is credited with inventing the modern periodic table of elements?",
    options: [
      "A) Dmitri Mendeleev",
      "B) Henry Moseley",
      "C) Jöns Jacob Berzelius",
      "D) Antoine Lavoisier",
    ],
    answer: "A) Dmitri Mendeleev",
  },
];
